<!--  PAGE NAME  -->
<section class="page-name">
    <h1>Ministérios</h1>
    <div class="bread-crumbs uppercase">
        <a href="/">Home</a>
        <a href="/ministerios">Ministérios</a>
    </div>
    <div class="image-wrapper images-bg">
        <img alt="" src="/assets/frontend/images/secondary-page/1.jpg">
    </div>
</section>
<!--  //PAGE NAME  -->

<!--  CONTENT  -->
<section class="blog-list single">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="ministry-block">
                            <div class="work-title">
                               <a class="name"><?=$ministry->title;?></a>
                            </div>
                            <?=$ministry->text;?>   
                            <div class="soc-button">
                                <span class="pull-left">Compartilhe !</span>
                                <a href="#" class="fa fa-google"></a>
                                <a href="#" class="fa fa-facebook"></a>
                                <a href="#" class="fa fa-twitter"></a>
                            </div>                       
                        </div>                      
                    </div>
                </div>
            </div>
        </section>
<!--  //CONTENT  -->