<div class="page-container">

    <div class="main-content">
           
        <form action="/admin/testemunhos/criar" method="POST" enctype="multipart/form-data" accept-charset="UTF-8" class="form-horizontal validate" novalidate="novalidate">
            
            <div class="page-title">

                <div class="title-env">
                    <h1 class="title">Cadastre um Testemunho</h1>
                    <p class="description">Cadastre um novo Testemunho.</p>
                </div>

                <div class="breadcrumb-env">
                    <button class="btn btn-success btn-lg" type="submit" name="submit"> Cadastrar </button>
                    <?=$form->render('csrf');?>
                </div>

            </div>

            <div class="row">

                <div class="col-sm-12">

                    <div class="panel panel-default">
                        <div class="panel-body">

                            <div class="row">
                               
                                <div class="col-md-12">
                                   
                                    <div class="form-group">
                                       <label class="control-label"><strong>Título</strong></label>
                                       <?=$form->render('title');?>
                                    </div>
                                    
                                    <div class="form-group">
                                       <label class="control-label"><strong>Autor</strong></label>
                                       <?=$form->render('author');?>
                                    </div>
                                    
                                    <div class="form-group" data-inputParent >
                                       <label class="control-label"><strong>Imagens</strong></label>
                                       <?=$form->render('file');?>
                                    </div>
                                    
                                    <div  data-add-group >
                                        
                                    </div>
                                    
                                    <div class="form-group">
                                        <button class="btn btn-purple btn-icon btn-icon-standalone btn-icon-standalone-right pull-right" type="button" data-add >
                                            <i class="fa-plus"></i><span>Adicionar Campo de Imagem</span>
                                        </button>
                                    </div>
                                    
                                </div>
                                
                            </div>
                            <div class="form-group">
                               <label class="control-label"><strong>Descrição</strong></label>
                               <?=$form->render('text');?>
                            </div>

                        </div>
                    </div>

                </div>

            </div>
                
            
        </form>

    </div>

</div>


<?php $this->flashSession->output(); ?>