<div class="page-container">

    <div class="main-content">
           
        <form action="/admin/artigos/alterar/<?=$this->dispatcher->getParam(0);?>" method="POST" enctype="multipart/form-data" accept-charset="UTF-8" class="form-horizontal validate" novalidate="novalidate">
            
            <div class="page-title">

                <div class="title-env">
                    <h1 class="title">Altere um Artigo</h1>
                    <p class="description">Altere as informações do  Artigo.</p>
                </div>

                <div class="breadcrumb-env">
                    <button class="btn btn-success btn-lg" type="submit" name="submit"> Alterar </button>
                    <?=$form->render('csrf');?>
                </div>

            </div>

            <div class="row">

                <div class="col-sm-12">

                    <div class="panel panel-default">
                        <div class="panel-body">

                            <div class="row">
                               
                                <div class="col-md-10">
                                   
                                    <div class="form-group">
                                       <label class="control-label"><strong>Título</strong></label>
                                       <?=$form->render('title');?>
                                    </div>
                                    
                                    <div class="form-group">
                                       <label class="control-label"><strong>Categoria</strong></label>
                                       <?=$form->render('category');?>
                                    </div>
                                    
                                    <div class="form-group">
                                       <label class="control-label"><strong>Imagem De Destaque</strong></label>
                                       <?=$form->render('file');?>
                                    </div>
                                    
                                </div>
                                
                                <div class="col-md-2">
                                   
                                    <label class="control-label"><strong>Pre-Visualização</strong></label>
                                    <img src="/assets/frontend/images/articles/<?=$image;?>" alt="" class="img-responsive img-thumbnail preview ">

                                </div>
                                
                            </div>
                            <div class="form-group">
                               <label class="control-label"><strong>Descrição</strong></label>
                               <?=$form->render('text');?>
                            </div>

                        </div>
                    </div>

                </div>

            </div>
                
            
        </form>

    </div>

</div>


<?php $this->flashSession->output(); ?>