<div class="page-container">

    <div class="main-content">

        <div class="row">
            <div class="col-sm-12">
                <a href="/admin/testemunhos/adicionar/">
                    <button class="btn btn-secondary btn-icon btn-icon-standalone btn-icon-standalone-right pull-right"><i class="fa-plus"></i><span>Adicionar</span></button>
                </a>
            </div>
            
            <div class="col-sm-12">

                <div class="xe-widget xe-conversations">
                    <div class="xe-bg-icon">
                        <i class="fa-quote-left"></i>
                    </div>
                    <div class="xe-header">
                        <div class="xe-icon">						
                            <i class="fa-quote-left"></i>
                        </div>
                        <div class="xe-label">
                            <h3>
                                Testemunhos
                                <small>Testemunhos cadastradas</small>
                            </h3>
                        </div>
                    </div>

                    <div class="xe-body">
                        <input type="text" class="form-control form-focus-info full-width" id="search_wdg" placeholder="Search ... ">
                        <ul class="list-unstyled" id="list-unstyled">

                            <?php foreach($testimonies as $testimony): ?>
                            <li>
                                <div class="xe-comment-entry">
                                    <div class="xe-comment"> 

                                        <div class="col-md-9">
                                            <a href="/admin/testemunhos/editar/<?=$testimony->_;?>" class="xe-user-name"> 
                                                <strong><?=$testimony->title;?></strong>
                                            </a>
                                            <div class="form-group inline">
                                                <span class="badge badge-primary" style="font-size: 12px">
                                                    <i class="fa-clock-o"></i> <?=(new DateTime($testimony->date))->format("d/m/Y \a\s H:i");?>
                                                </span>
                                            </div>
                                            <p><?=substr($testimony->text,0,255);?>...</p>
                                        </div>
                                        <div class="col-md-3">
                                            <a href="/admin/testemunhos/remover/<?="{$testimony->_}/{$csrf}";?>">
                                                <button class="btn btn-danger btn-icon btn-icon-standalone btn-icon-standalone-right pull-right"><i class="fa-close"></i><span>Remover</span></button>
                                            </a>
                                            <a href="/admin/testemunhos/editar/<?=$testimony->_;?>">
                                                <button class="btn btn-info btn-icon btn-icon-standalone btn-icon-standalone-right pull-right"><i class="fa-pencil"></i><span>Alterar</span></button>
                                            </a>
                                        </div>

                                    </div> 
                                </div>
                            </li>
                            <?php endforeach; ?>

                        </ul>
                        </div>

                    </div>

                </div>
            
			</div>

    </div>

</div>
<?php $this->flashSession->output(); ?>