<!--  PAGE NAME  -->
<section class="page-name">
    <h1>PEdidos de oração</h1>
    <div class="bread-crumbs uppercase">
        <a href="/">Home</a>
        <a href="/artigos">artigos</a>
        <a href="/testemunhos">testemunhos</a>
    </div>
    <div class="image-wrapper images-bg">
        <img alt="" src="/assets/frontend/images/secondary-page/1.jpg">
    </div>  
</section>
<!--  //PAGE NAME  -->

<!--  CONTEUDO  -->
<section class="blog-list">
    <div class="container">
        <div class="row">

            <div class="col-md-12">

                <div class="work-title center">
                    <div class="name">Envie Seu Pedido de Oração !</div>
                </div>
                
                <div class="row">
                    
                    <form id="ajax-request-form" action="javascript:void(0);" class="form-alt">
                        <div class="col-md-12">
                            <input type="text" name="name" placeholder="Nome">
                        </div>
                        <div class="col-md-12">
                            <input type="text" name="email" placeholder="E-mail">
                        </div>
                        <div class="col-md-12">
                            <input type="text" name="phone" placeholder="Telefone">
                        </div>
                        <div class="col-md-6">
                            <input type="text" name="state" placeholder="Estado">
                        </div>
                        <div class="col-md-6">
                            <input type="text" name="city" placeholder="Cidade">
                        </div>
                        <div class="col-lg-9 col-md-8 col-sm-9">
                            <textarea name="message" placeholder="Pedido"></textarea>
                        </div>
                        <div class="col-lg-3 col-md-4 col-sm-3">
                            <a href="#" class="button var3" style="height: 140px;width: 100%;"><span>envie seu <br> pedido agora!</span></a>
                        </div>
                    </form>
                    
                </div>

            </div>

        </div>
    </div>
</section>
<!--  //CONTEUDO  -->