<!--  PAGE NAME  -->
<section class="page-name">
    <h1>Videos</h1>
    <div class="bread-crumbs uppercase">
        <a href="/">Home</a>
        <a href="./albums">Albums de fotos</a>
        <a href="./audios">Audios</a>
    </div>
    <div class="image-wrapper images-bg">
        <img alt="" src="/assets/frontend/images/secondary-page/1.jpg">
    </div>  
</section>
<!--  //PAGE NAME  -->

<!--  CONTEUDO  -->
<section class="blog-list">
    <div class="container">
        <div class="row">
          
            <?php foreach( $videos as $video ): ?>
            <div class="col-lg-3 col-md-4 col-sm-12">
                <div class="blog-block" style="padding-left:0">
                    <div class="responsive-video">
                        <iframe class="full-width" src="//www.youtube.com/embed/<?=$video->vi;?>" frameborder="0" allowfullscreen ></iframe>
                    </div>
                    <a class="name uppercase" href="#"><?=$video->title;?></a>
                    <div class="position"></div>
                    <hr> 
                </div>
            </div>
            <?php endforeach; ?>
        
        </div>
    </div>
</section>
<!--  //CONTEUDO  -->