<!--  PAGE NAME  -->
<section class="page-name">
    <h1>Videos</h1>
    <div class="bread-crumbs uppercase">
        <a href="/">Home</a>
        <a href="./albums">Albums de fotos</a>
        <a href="./audios">Audios</a>
    </div>
    <div class="image-wrapper images-bg">
        <img alt="" src="/assets/frontend/images/secondary-page/1.jpg">
    </div>  
</section>
<!--  //PAGE NAME  -->

<!--  CONTEUDO  -->
<section class="blog-list">
    <div class="container">
        <div class="row">
           
            <?php foreach( $videos as $video ): ?>
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="blog-block">
                    <div class="date">
                        <div class="day"><?=(new DateTime($video->date))->format("d")?></div>
                        <div class="other">
                        <?php 
                        switch((new DateTime($video->date))->format("m"))
                        {
                            case 1  : $month = "Janeiro"; break;
                            case 2  : $month = "Fevereiro"; break;
                            case 3  : $month = "Março"; break;
                            case 4  : $month = "Abril"; break;
                            case 5  : $month = "Maio"; break;
                            case 6  : $month = "Junho"; break;
                            case 7  : $month = "Julho"; break;
                            case 8  : $month = "Agosto"; break;
                            case 9  : $month = "Setembro"; break;
                            case 10 : $month = "Outubro"; break;
                            case 11 : $month = "Novembro"; break;
                            case 12 : $month = "Dezembro"; break;

                        }
                        echo "{$month}, ".(new DateTime($video->date))->format("Y");
                        ?>
                        </div>
                    </div>
                    
                    <iframe class="full-width" height="500" src="//www.youtube.com/embed/<?=$video->vi;?>" frameborder="0" allowfullscreen ></iframe>
                    <a class="name uppercase" href="#"><?=$video->title;?></a>
                    <div class="position"></div>
                    <hr>                            
                </div>
            </div>
            <?php endforeach; ?>
            
        </div>
    </div>
</section>
<!--  //CONTEUDO  -->