<div class="page-container">

    <div class="main-content">

        <div class="row">

            <div class="col-md-12">

                <ul class="nav nav-tabs nav-tabs-justified">
                    <li class="active">
                        <a href="#one" data-toggle="tab">
                            <span class="visible-xs"><i class="fa-home"></i></span>
                            <span class="hidden-xs">Boletins</span>
                        </a>
                    </li>
                    <li>
                        <a href="#two" data-toggle="tab">
                            <span class="visible-xs"><i class="fa-tag"></i></span>
                            <span class="hidden-xs">Categorias de Boletins</span>
                        </a>
                    </li>
                    <li>
                        <a href="#three" data-toggle="tab">
                            <span class="visible-xs"><i class="fa-user"></i></span>
                            <span class="hidden-xs">Autores de Boletins</span>
                        </a>
                    </li>
                </ul>

                <div class="tab-content">
                
                    <div class="tab-pane active" id="one">
                        <div class="row">
                            <div class="col-sm-12">

                                <div class="xe-widget xe-conversations">
                                    <div class="xe-header">
                                        <div class="xe-icon">						
                                            <i class="fa-newspaper-o"></i>
                                        </div>
                                        <div class="xe-label">
                                            <h3>Boletins <small>Boletins cadastradas</small></h3>
                                        </div>
                                        <a href="/admin/gcem/adicionar/boletim">
                                            <button class="btn btn-secondary btn-icon btn-icon-standalone btn-icon-standalone-right pull-right">
                                                <i class="fa-plus"></i><span>Adicionar Boletim</span>
                                            </button>
                                        </a>
                                    </div>

                                    <div class="xe-body">
                                        <input type="text" class="form-control form-focus-info full-width" id="search_wdg" placeholder="Search ... ">
                                        <ul class="list-unstyled" id="list-unstyled">

                                        <?php foreach($newsletters as $newsletter): ?>
                                            <li>
                                                <div class="xe-comment-entry">
                                                    <div class="xe-comment"> 

                                                        <div class="col-md-9">
                                                            <a href="/admin/gcem/editar/boletim/<?=$newsletter->_;?>" class="xe-user-name"> 
                                                                <strong><?=$newsletter->title;?></strong>
                                                            </a>
                                                            <div class="form-group inline">
                                                                <span class="badge badge-primary" style="font-size: 12px">
                                                                    <i class="fa-clock-o"></i> <?=(new DateTime($newsletter->date))->format("d/m/Y \a\s H:i");?>
                                                                </span>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-3">
                                                            <a href="/admin/gcem/remover/<?="{$newsletter->_}/{$csrf}";?>">
                                                                <button class="btn btn-danger btn-icon btn-icon-standalone btn-icon-standalone-right pull-right"><i class="fa-close"></i><span>Remover</span></button>
                                                            </a>
                                                            <a href="/admin/gcem/editar/boletim/<?=$newsletter->_;?>">
                                                                <button class="btn btn-info btn-icon btn-icon-standalone btn-icon-standalone-right pull-right"><i class="fa-pencil"></i><span>Alterar</span></button>
                                                            </a>
                                                        </div>

                                                    </div> 
                                                </div>
                                            </li>
                                        <?php endforeach; ?>

                                        </ul>
                                    </div>

                                </div>

                            </div>

                        </div>

                    </div>
                    <div class="tab-pane" id="two">
                        <div class="row">
                            <div class="col-sm-12">

                                <div class="xe-widget xe-conversations">
                                    <div class="xe-header">
                                        <div class="xe-icon">						
                                            <i class="fa-newspaper-o"></i>
                                        </div>
                                        <div class="xe-label">
                                            <h3>Categorias de Boletins <small>Categorias de Boletins cadastradas</small></h3>
                                        </div>
                                        <a href="/admin/gcem/adicionar/categoria">
                                            <button class="btn btn-secondary btn-icon btn-icon-standalone btn-icon-standalone-right pull-right">
                                                <i class="fa-plus"></i><span>Adicionar Categoria</span>
                                            </button>
                                        </a>
                                    </div>

                                    <div class="xe-body">
                                        <input type="text" class="form-control form-focus-info full-width" id="search_wdg" placeholder="Search ... ">
                                        <ul class="list-unstyled" id="list-unstyled">

                                        <?php foreach($categories as $category): ?>
                                            <li>
                                                <div class="xe-comment-entry">
                                                    <div class="xe-comment"> 

                                                        <div class="col-md-9">
                                                            <a href="/admin/gcem/editar/categoria/<?=$category->_;?>" class="xe-user-name"> 
                                                                <strong><?=$category->title;?></strong>
                                                            </a>
                                                        </div>
                                                        <div class="col-md-3">
                                                            <a href="#" data-modal="/admin/gcem/modal/category/remove" data-ide="<?=$category->_;?>" >
                                                                <button class="btn btn-danger btn-icon btn-icon-standalone btn-icon-standalone-right pull-right"><i class="fa-close"></i><span>Remover</span></button>
                                                            </a>
                                                            <a href="#" data-modal="/admin/gcem/modal/category/modify" data-ide="<?=$category->_;?>">
                                                                <button class="btn btn-info btn-icon btn-icon-standalone btn-icon-standalone-right pull-right"><i class="fa-pencil"></i><span>Alterar</span></button>
                                                            </a>
                                                        </div>

                                                    </div> 
                                                </div>
                                            </li>
                                        <?php endforeach; ?>

                                        </ul>
                                    </div>

                                </div>

                            </div>

                        </div>

                    </div>
                    <div class="tab-pane" id="three">
                        <div class="row">
                            <div class="col-sm-12">

                                <div class="xe-widget xe-conversations">
                                    <div class="xe-header">
                                        <div class="xe-icon">						
                                            <i class="fa-newspaper-o"></i>
                                        </div>
                                        <div class="xe-label">
                                            <h3>Autores de Boletins <small>Autores de Boletins cadastradas</small></h3>
                                        </div>
                                        <a href="/admin/gcem/adicionar/autor">
                                            <button class="btn btn-secondary btn-icon btn-icon-standalone btn-icon-standalone-right pull-right">
                                                <i class="fa-plus"></i><span>Adicionar Autor</span>
                                            </button>
                                        </a>
                                    </div>

                                    <div class="xe-body">
                                        <input type="text" class="form-control form-focus-info full-width" id="search_wdg" placeholder="Search ... ">
                                        <ul class="list-unstyled" id="list-unstyled">

                                        <?php foreach($authors as $author): ?>
                                            <li>
                                                <div class="xe-comment-entry">
                                                    <div class="xe-comment"> 

                                                        <div class="col-md-9">
                                                            <a href="/admin/gcem/editar/autor/<?=$author->_;?>" class="xe-user-name"> 
                                                                <strong><?=$author->name;?></strong>
                                                            </a>
                                                        </div>
                                                        <div class="col-md-3">
                                                            <a href="#" data-modal="/admin/gcem/modal/author/remove" data-ide="<?=$author->_;?>" >
                                                                <button class="btn btn-danger btn-icon btn-icon-standalone btn-icon-standalone-right pull-right"><i class="fa-close"></i><span>Remover</span></button>
                                                            </a>
                                                            <a href="#" data-modal="/admin/gcem/modal/author/modify" data-ide="<?=$author->_;?>" >
                                                                <button class="btn btn-info btn-icon btn-icon-standalone btn-icon-standalone-right pull-right"><i class="fa-pencil"></i><span>Alterar</span></button>
                                                            </a>
                                                        </div>

                                                    </div> 
                                                </div>
                                            </li>
                                        <?php endforeach; ?>

                                        </ul>
                                    </div>

                                </div>

                            </div>

                        </div>

                    </div>

                </div>


            </div>

        </div>

    </div>

</div>
<!-- Modal -->
<div class="modal fade" id="modal">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Atenção !</h4>
            </div>

            <div id="result">
                
                
            </div>
        </div>
    </div>
</div>
<?php $this->flashSession->output(); ?>