<!--  PAGE NAME  -->
<section class="page-name" data-scroll-index="1">
    <h1>ctl</h1>
    <div class="bread-crumbs uppercase">
        <a href="/">Home</a>
        <a href="/gcem">Sobre o GCEM</a>
        <a href="/gcem/boletins">Boletins</a>
        <a href="/gcem/mapa">gcem mais próximo</a>
    </div>
    <div class="image-wrapper images-bg">
        <img alt="" src="/assets/frontend/images/secondary-page/1.jpg">
    </div>  
</section>
<!--  //PAGE NAME  -->

<!--  CONTENT -->
<section class="blog-list">
    <div class="container">
        <div class="row">

            <div class="col-md-12 text-center">
                <h3 class="gcem-title"> CTL </h3>
            </div>
            
            <div class="col-md-12 theme-color">
                <h3><strong>Propósito Geral do CTL: </strong></h3>
                <p>Capacitar cada participante para um estilo de vida de crescimento pessoal contínuo (espiritual, emocional, familiar, profissional e ministerial), desenvolvendo sua visão e habilidades para servir, evangelizar e fazer discípulos no contexto da célula (GCEM).</p>

                <h3><strong>Para quem é o CTL:</strong></h3>
                <p><i class="fa fa-circle"></i>Para todos aqueles que compreenderam que foram chamados por Deus para fazerem parte da grande Missão que Ele está realizando na terra, o Ministério da Reconciliação (Evangelizar, Discipular, Capacitar e Enviar) e que desejam ser melhor capacitados para esta obra.</p>

                <p><i class="fa fa-circle"></i>Para todos aqueles que estão comprometidos com o GCEM do qual fazem parte.</p>


                <p><b>Observação:</b> É necessário ter a indicação do Dirigente do GCEM.</p>

                <p><b>“18Ora, tudo provém de Deus, que nos reconciliou consigo mesmo por meio de Cristo e nos deu o ministério da reconciliação, 19a saber, que Deus estava em Cristo reconciliando consigo o mundo, não imputando aos homens as suas transgressões, e nos confiou a palavra da reconciliação” – 2Coríntios 5:18-19</b></p>


            </div>

        </div>
        
    </div>
</section>
<!--  //CONTENT  -->