<!--  PAGE NAME  -->
<section class="page-name" data-scroll-index="1">
    <h1>sobre o gcem</h1>
    <div class="bread-crumbs uppercase">
        <a href="/">Home</a>
        <a href="/gcem/boletins">Boletins</a>
        <a href="/gcem/mapa">gcem mais próximo</a>
        <a href="/gcem/ctl">ctl</a>
    </div>
    <div class="image-wrapper images-bg">
        <img alt="" src="/assets/frontend/images/secondary-page/1.jpg">
    </div>  
</section>
<!--  //PAGE NAME  -->

<!--  CONTENT -->
<section class="blog-list">
    <div class="container">
        <div class="row">

            <div class="col-md-12 text-center">
                <h3 class="gcem-title"> O que é </h3>
            </div>
            
            <div class="col-md-12 theme-color">
                <p>Nossos pequenos grupos ou células são chamados de GCEM (Grupo de Comunhão, Edificação e Multiplicação).</p>

                <p>O GCEM é um grupo que se reúne nos lares, composto de 10 a 15 pessoas no máximo, com a finalidade de promover comunhão e edificação entre os irmãos, e de dar atenção especial aos novos convertidos, culminando com a multiplicação do grupo; ou seja, com a abertura de um novo grupo que será dirigido por alguém que se desenvolveu dentro do próprio GCEM.</p>

                <p>A igreja é o lugar onde as pessoas devem desenvolver relacionamentos significativos, baseados no amor fraternal, com o objetivo de alcançar e abençoar as pessoas.</p>

                <p>O grupo existe para cumprir este papel. Lendo atos dos apóstolos, descobrimos que a igreja nasceu com estas características: (<b>Atos 2:46-47</b>).</p>
            </div>

        </div>
        <div class="row">

            <div class="col-md-12 text-center">
                <h3 class="gcem-title"> A Importância do GCEM </h3>
            </div>
            
            <div class="col-md-12 theme-color">
                <p>O GCEM é o local ideal para a prática da Teologia, Visão e Missão da Comunidade da Graça, pois é no pequeno grupo que estes princípios podem ser melhor aplicados, acompanhados e aperfeiçoados na vida de cada membro, através do pastoreio, comunhão e discipulado.</p>

                <p>A Teologia, a Visão, a Missão e o Modelo IDE convergem totalmente para o GCEM: primeiramente os membros tem que experimentar o novo nascimento para poder viver dentro dos valores da Visão, e então juntos, na comunhão do amor, desempenhar a Missão de fazer discípulos de Cristo, seguindo as orientações e disposições da nossa estratégia (Modelo IDE).</p>

                <p>A nossa Visão de igreja família só pode ser plenamente vivida no contexto do pequeno grupo, pois ali num convívio de crescente amizade, intimidade e aliançados é que seus membros poderão praticar os valores da Visão que se sintetizam numa só palavra: RELACIONAMENTOS.</p>

                <p>Desta forma a Teologia se expressa através do desafio de levar cada membro do GCEM a experiência do novo nascimento. Cada um deve ser regenerado, frutífero, caso contrário, o grupo será um fracasso.</p>
                <p>A Visão se expressa nos relacionamentos. Primeiramente cada membro deve ter um relacionamento com Deus, e então relacionamento com a sua família, com os seus irmãos e com os ímpios. Se expressa no viver em amor. Os membros devem aprender os relacionamentos recíprocos para terem relacionamentos saudáveis.</p>
                <p>A Missão se expressa no preparo de um novo líder. No GCEM os membros deverão ser desafiados a fazer discípulos, ao IDE, ao discipulado um a um, deverão ser capacitados e treinados para serem líderes e também multiplicarem o GCEM.</p>
            </div>

        </div>
        <div class="row theme-color">

            <div class="col-md-12 text-center">
                <h3 class="gcem-title"> A Dinâmica do GCEM </h3>
            </div>
            
            <div class="col-md-12">
                <p>O grupo é lugar de relacionamento, de atendimento das pessoas, de oração e de multiplicação. A reunião do GCEM deve estar baseada na dinâmica dos 4 E’s:</p>
            </div>
            
            <div class="col-md-6 col-sm-12">
                <h3><b class="uppercase">encontro</b></h3>
                <p>O Encontro é o primeiro contato das pessoas umas com as outras, quando chegam ao grupo. Deve haver uma interação entre os membros do grupo antes do tempo reservado para os cânticos e o compartilhar da Palavra e oração. O quebra-gelo é uma oportunidade das pessoas falarem e sentirem-se absolutamente a vontade no grupo. Sentindo-se a vontade para falar sobre assuntos simples, elas poderão falar sobre assuntos mais particulares posteriormente.
O dirigente deverá buscar a Deus para saber qual a melhor pergunta para o quebra-gelo, pois ele levará as pessoas a se abrirem e ficarem mais soltas e receptivas para a continuidade da reunião.</p>
            </div>
            <div class="col-md-6 col-sm-12">
                <h3><b class="uppercase">exaltação</b></h3>
                <p>A Exaltação é o momento de o grupo agradecer e elogiar a Deus; louvar e exaltar ao Senhor Jesus Cristo por todos os benefícios recebidos. Louvar a Deus, exalta-lo, bendize-lo e honra-lo com cânticos e palavras de amor é essencial para a operação do Espírito Santo manifestando a presença do Senhor. O dirigente deverá estar atento, pois este é o momento muito apropriado para levar as pessoas ao batismo no Espírito Santo (Efésios 5:18-20).</p>
            </div>

        </div>
        <div class="row theme-color">
            
            <div class="col-md-5 col-sm-12">
                <h3><b class="uppercase">edificação</b></h3>
                <p>A Palavra de Deus, sintetizada no boletim deve ser usado como uma ferramenta que promova edificação e interação entre os membros do grupo. Não deve ser lido como em uma missa. O papel do dirigente nesta parte não será o de pregador ou de mestre, mas sim de facilitador da participação de todos, para que haja compartilhamento e mútua edificação. No final deste período o dirigente deverá levar o grupo a orar pelas necessidades uns dos outros.</p>
            </div>
            <div class="col-md-7 col-sm-12">
                <h3><b class="uppercase">evangelismo</b></h3>
                <p>A ênfase principal do GCEM deve ser a grande comissão dada por Jesus a todos nós: “Ide, portanto, fazei discípulos de todas as nações, batizando-os em nome do Pai, e do Filho, e do Espírito Santo” - Mateus 28:19. A última etapa da reunião deve privilegiar o trabalho evangelístico. O alvo é alcançar os não cristãos através de cada membro do GCEM. O dirigente deve demonstrar para o grupo, com palavras, oração e planos, que todos devem estar envolvidos no crescimento e multiplicação do grupo.
Por outro lado, se o dirigente não se preparar convenientemente, através da comunhão íntima com o Senhor, toda esta dinâmica será vazia, fria e sem vida. Para que a presença de Jesus seja realmente manifestada, “...onde dois ou três estiverem reunidos em meu nome, eu estarei no meio deles...”, é necessário que o dirigente invista diariamente num tempo precioso na Palavra, na oração, na adoração e louvor, na intercessão e na guerra espiritual, tudo isto acompanhado de um plano de jejum.</p>
            </div>
        </div>
        <div class="row theme-color">
            <div class="col-md-12">
                <h3><b>Há pelo menos cinco funções indispensáveis para que um grupo seja sadio e produtivo:</b></h3>

                    <p><i class="fa fa-circle"></i>Evangelismo e Integração</p>
                    <p><i class="fa fa-circle"></i>Pastoreio</p>
                    <p><i class="fa fa-circle"></i>Comunhão</p>
                    <p><i class="fa fa-circle"></i>Discipulado e Formação de Líderes</p>
                    <p><i class="fa fa-circle"></i>Crescimento e Multiplicação</p>

                <h3><strong>Estas funções do GCEM deverão ser as prioridades a serem praticadas pelo dirigente, auxiliares e membros do GCEM.</strong></h3>
                <h3><b>Para desenvolver com sucesso suas funções, o dirigente precisa desenvolver os seguintes hábitos:</b></h3>

                    <p><i class="fa fa-circle"></i>Sonho: sonhe em liderar um grupo saudável, que cresce e se multiplica.</p>
                    <p><i class="fa fa-circle"></i>Oração: ore diariamente pelos membros do grupo.</p>
                    <p><i class="fa fa-circle"></i>Convite: convide semanalmente pessoas novas para visitar o grupo.</p>
                    <p><i class="fa fa-circle"></i>Contato: contate regularmente os membros do grupo.</p>
                    <p><i class="fa fa-circle"></i>Preparo: prepare-se para o encontro do grupo.</p>
                    <p><i class="fa fa-circle"></i>Mentoreamento: mentoreie um auxiliar de líder.</p>
                    <p><i class="fa fa-circle"></i>Comunhão: planeje atividades de comunhão do grupo.</p>
                    <p><i class="fa fa-circle"></i>Crescimento: comprometa-se com o crescimento pessoal.</p>

            </div>
        </div>
    </div>
</section>
<!--  //CONTENT  -->