<!--  PAGE NAME  -->
<section class="page-name" data-scroll-index="1" style="margin-bottom:0;">
    <h1>gcem mais próximo</h1>
    <div class="bread-crumbs uppercase">
        <a href="/">Home</a>
        <a href="/gcem">Sobre o GCEM</a>
        <a href="/gcem/boletins">Boletins</a>
        <a href="/gcem/ctl">ctl</a>
    </div>
    <div class="image-wrapper images-bg">
        <img alt="" src="/assets/frontend/images/secondary-page/1.jpg">
    </div>  
</section>
<!--  //PAGE NAME  -->

<!--  CONTENT -->
<section class="blog-list" id="googleMap" style="height:500px;margin-bottom:0;"></section>
<!--  //CONTENT  -->