<!--  PAGE NAME  -->
<section class="page-name" data-scroll-index="1">
    <h1>testemunhos</h1>
    <div class="bread-crumbs uppercase">
        <a href="/">Home</a>
        <a href="/artigos">artigos</a>
        <a href="/pedidos">pedidos de oração</a>
    </div>
    <div class="image-wrapper images-bg">
        <img alt="" src="/assets/frontend/images/secondary-page/1.jpg">
    </div>
</section>
<!--  //PAGE NAME  -->

<!--  CONTENT -->
<section class="blog-list">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <?php foreach( $testimonies as $testimony ): ?>
                <div class="blog-block" data-testimony-block >
                    <div class="date">
                        <div class="date">
                            <div class="day"><?=(new DateTime($testimony->date))->format("d");?></div>
                            <div class="other">
                            <?php
                            switch((new DateTime($testimony->date))->format("m"))
                            {
                                case 1  : $month = "Janeiro"; break;
                                case 2  : $month = "Fevereiro"; break;
                                case 3  : $month = "Março"; break;
                                case 4  : $month = "Abril"; break;
                                case 5  : $month = "Maio"; break;
                                case 6  : $month = "Junho"; break;
                                case 7  : $month = "Julho"; break;
                                case 8  : $month = "Agosto"; break;
                                case 9  : $month = "Setembro"; break;
                                case 10 : $month = "Outubro"; break;
                                case 11 : $month = "Novembro"; break;
                                case 12 : $month = "Dezembro"; break;
                            }
                            echo "{$month}, ".(new DateTime($testimony->date))->format("Y");
                            ?>
                            </div>
                        </div>
                    </div>
                    <a class="name" href="/testemunhos/post/<?=$testimony->urlrequest;?>"><?=$testimony->title;?></a>
                    <div class="position">Enviado Por: <?=$testimony->author;?></div>
                    <?=substr($testimony->text,0,255);?> ...
                    <div class="clearfix">
                        <a class="pull-left read-more" href="/testemunhos/post/<?=$testimony->urlrequest;?>">
                            <em class="fa fa-chevron-right"></em>
                            Continue Lendo
                        </a>
                    </div>
                    <hr>
                </div>
                <?php endforeach; ?>
                <div data-testimonies-results ></div>
                <button class="button var3 full-width" data-testimonies-fetch > Carregar Mais Testemunhos </button>

            </div>
        </div>
    </div>
</section>
<!--  //CONTENT  -->
