<div class="page-container">

    <div class="main-content">
           
        <form action="/admin/pastores/criar" method="POST" enctype="multipart/form-data" accept-charset="UTF-8" class="form-horizontal validate" novalidate="novalidate">
            
            <div class="page-title">

                <div class="title-env">
                    <h1 class="title">Cadastre um pastor</h1>
                    <p class="description">Cadastre um novo pastor.</p>
                </div>

                <div class="breadcrumb-env">
                    <button class="btn btn-success btn-lg" type="submit" name="submit"> Cadastrar </button>
                    <?=$form->render('csrf');?>
                </div>

            </div>

            <div class="row">

                <div class="col-sm-10">

                    <div class="panel panel-default">
                        <div class="panel-body">

                            <div class="form-group">
                               <label class="control-label"><strong>Nome Completo</strong></label>
                               <?=$form->render('name');?>
                            </div>
                            <div class="form-group">
                                <label class="control-label"><strong>Foto do Pastor</strong></label>
                               <?=$form->render('file');?>
                            </div>

                        </div>
                    </div>

                </div>

                <div class="col-sm-2">

                    <div class="panel panel-default">
                        <div class="panel-body">

                            <div class="form-group">
                                <label class="control-label"><strong>Pre-Visualização:</strong></label><br>
                                <img src="/assets/backend/images/banner-modal.jpg" alt="" class="img-responsive img-thumbnail preview preview_img">
                            </div>

                        </div>
                    </div>

                </div>

            </div>
                
            
        </form>

    </div>

</div>

<?php $this->flashSession->output(); ?>