<div class="page-container">

    <div class="main-content">

        <div class="row">
            <div class="col-sm-12">
                <a href="/admin/pastores/adicionar/">
                    <button class="btn btn-secondary btn-icon btn-icon-standalone btn-icon-standalone-right pull-right"><i class="fa-plus"></i><span>Adicionar</span></button>
                </a>
            </div>
            
            <div class="col-sm-12">
					
				<div class="xe-widget xe-conversations">
                    <div class="xe-bg-icon">
                        <i class="fa-users"></i>
                    </div>
                    <div class="xe-header">
                        <div class="xe-icon">						
                            <i class="fa-users"></i>
                        </div>
                        <div class="xe-label">
                            <h3>
                                Pastores
                                <small>Pastores cadastrados</small>
                            </h3>
                        </div>
                    </div>
                    
				    <div class="xe-body">
				        <input type="text" class="form-control form-focus-info full-width" id="search_wdg" placeholder="Search ... ">
                        <ul class="list-unstyled" id="list-unstyled">
                            <?php foreach($members as $member): ?>
                            <li>
                                <div class="xe-comment-entry">
                                    <a href="/admin/pastores/editar/<?=$member->_;?>" class="xe-user-img">
                                        <img src="/assets/frontend/images/team/<?=$member->image;?>" class="img-circle" width="50" height="50">
                                    </a>
                                    <div class="xe-comment"> 
                                        
                                        <div class="col-md-9">
                                            <a href="/admin/pastores/editar/<?=$member->_;?>" class="xe-user-name"> 
                                                <strong><?=$member->name;?></strong>
                                            </a>
                                        </div>
                                        <div class="col-md-3">
                                            <a href="/admin/pastores/remover/<?="{$member->_}/{$csrf}";?>">
                                                <button class="btn btn-danger btn-icon btn-icon-standalone btn-icon-standalone-right pull-right"><i class="fa-close"></i><span>Remover</span></button>
                                            </a>
                                            <a href="/admin/pastores/editar/<?=$member->_;?>">
                                                <button class="btn btn-info btn-icon btn-icon-standalone btn-icon-standalone-right pull-right"><i class="fa-pencil"></i><span>Alterar</span></button>
                                            </a>
                                        </div>
                                        
                                    </div> 
                                </div>
                            </li>
                            <?php endforeach; ?>

                        </ul>
						</div>
                        
					</div>
					
				</div>
			</div>

    </div>

</div>
<?php $this->flashSession->output(); ?>