<!--  PAGE NAME  -->
<section class="page-name" data-scroll-index="1">
    <h1>a associação</h1>
    <div class="bread-crumbs uppercase">
        <a href="./teologia">teologia</a>
        <a href="./visao">Visão</a>
        <a href="./valores">os valores da visão</a>
        <a href="./missao">missão</a>
        <a href="./familia">a família de deus</a>
        <a href="./modelo">modelo ide</a>
        <a href="./logo">significado da logo</a>
        <a href="./fundacao">a fundação</a>
        <a href="./declaracao">declaração de fé</a>
    </div>
    <div class="image-wrapper images-bg">
        <img alt="" src="/assets/frontend/images/secondary-page/1.jpg">
    </div>  
</section>
<!--  //PAGE NAME  -->

<!--  CONTENT  -->
<section class="blog-list">
    <div class="container">
        <div class="row">

            <div class="col-md-12 theme-color">

                <p>A Associação foi criada diante do crescimento e da diversificação das Igrejas Comunidade da Graça no Brasil e no exterior. A expansão da Igreja demandou  uma Instituição promotora da unidade da visão, direção e cooperação entre todas as igrejas.</p>

                <p>A Associação é uma entidade sem fins lucrativos, composta por igrejas cristãs evangélicas e entidades de promoção e desenvolvimento social, educacional e cultural.</p>

                <p>A Associação existe com o propósito de efetivar a cooperação de várias comunidades locais, visando missão e objetivos comuns: </p>

                    <p><i class="fa fa-circle"></i>Estabelecimento de igrejas locais dentro e fora do território nacional;</p>
                    <p><i class="fa fa-circle"></i>Programas educacionais de treinamento e ensino formal;</p>
                    <p><i class="fa fa-circle"></i>Programas de radiodifusão, internet e outros meios de comunicação;</p>
                    <p><i class="fa fa-circle"></i>Publicação de livros, jornais, revistas, CDs, vídeos e afins;</p>
                    <p><i class="fa fa-circle"></i>Eventos culturais, seminários, simpósios e palestras.</p>

            </div>

        </div>
    </div>
</section>
<!--  //CONTENT  -->