<!--  PAGE NAME  -->
<section class="page-name" data-scroll-index="1">
    <h1>declaração de fé</h1>
    <div class="bread-crumbs uppercase">
        <a href="./teologia">teologia</a>
        <a href="./visao">Visão</a>
        <a href="./valores">os valores da visão</a>
        <a href="./missao">missão</a>
        <a href="./familia">a família de deus</a>
        <a href="./modelo">modelo ide</a>
        <a href="./logo">significado da logo</a>
        <a href="./associacao">a associação</a>
        <a href="./fundacao">a fundação</a>
    </div>
    <div class="image-wrapper images-bg">
        <img alt="" src="/assets/frontend/images/secondary-page/1.jpg">
    </div>  
</section>
<!--  //PAGE NAME  -->

<!--  CONTEUDO  -->
<section class="blog-list">
    <div class="container">
        <div class="row">

            <div class="col-md-12 theme-color">

            <h3><strong>Confessamos que cremos:</strong></h3>

            <h3><b>I. O Deus Trino</b></h3>

            <p>1. Em um só Deus, que subsiste eternamente em três pessoas: o Pai, criador de todo o universo, o Filho, Jesus Cristo único Senhor e Salvador de toda humanidade, e o Espírito Santo, que nos capacita a viver a vida cristã. (Marcos 1.9-11; Mateus 28.11 e II Coríntios 13.13).</p>

            <h3><b>II. Jesus Cristo</b></h3>

            <p>2. Na encarnação do Verbo, que era Deus e habitava com Deus, e que na pessoa de Jesus Cristo, o Filho unigênito do Pai, veio ao mundo para salvar toda humanidade da lei do pecado e da morte, como expressão máxima do amor de Deus. (João 1.1-14 e 29).</p>

            <p>3. Na concepção virginal de Jesus, que nasceu em Israel durante o reinado de Herodes na Judéia, morreu sob o governo romano de Poncio Pilatos na Palestina, mas que ressuscitou ao terceiro dia, foi elevado aos céus onde está reinando exaltado e glorificado como único Senhor dos vivos e mortos, intercedendo pela salvação de todos. (Mateus 2.1; Lucas 27.11-14; Atos 2.32-36 e Hebreus 7.25).</p>

            <h3><b>III. O Espírito Santo</b></h3>

            <p>4. No Espírito Santo, a Terceira pessoa da Santíssima Trindade, que sendo absolutamente igual ao Pai e ao Filho, tem uma atuação imprescindível para a salvação do homem; desde o convencimento do pecado levando ao arrependimento, agindo juntamente com a Palavra na regeneração dos pecadores e habitando no interior de cada salvo, capacitando-o a expressar a vida de Cristo. (João 14.15-18 e 16.5-15; Tito 2.4-7 e Romanos 8.1-27).</p>

            <h3><b>IV. A Palavra de Deus</b></h3>

            <p>5. Na Palavra de Deus, registrada na Bíblia Sagrada por inspiração divina, como única regra infalível de fé normativa para a vida e o caráter cristão. (II Pedro 1.19-21 e Sl 119.105).</p>

            <h3><b>V. O Propósito Eterno de Deus</b></h3>

            <p>6. No Propósito Eterno de Deus, que criou o homem à sua imagem e semelhança, para que este expressasse a glória divina perante o universo, governasse toda a criação implantando o Reino de Deus na terra e se multiplicasse para realizar o sonho do coração do Pai: “ter uma família com muitos filhos semelhantes a Jesus”. (Gênesis 1.26-28).</p>

            <h3><b>VI. A Queda do Homem</b></h3>

            <p>7. Na queda do ser humano no pecado e sua conseqüente condenação eterna, através da transgressão do mandamento divino, que o levou a perder a glória de Deus, tornando-o incapaz de realizar o Propósito Eterno de Deus para a sua vida. (Gênesis 3 e Romanos 3.23).</p>

            <h3><b>VII. A Salvação Pela Graça</b></h3>

            <p>8. No sacrifício de Cristo na cruz do Calvário, único, perfeito, que não pode ser repetido, e totalmente suficiente para salvar todo homem e o homem todo: espírito, alma e corpo. (Hebreus 10.10-14).</p>

            <p>9. No evangelho do Senhor Jesus Cristo que nos atesta sobre a eleição, predestinação, redenção, regeneração e justificação de todos os homens em Cristo, aos quais devem ser pregadas estas boas novas para arrependimento e fé, a fim de que se apropriem de todas as riquezas da graça de Deus, cuja rejeição implicará na condenação eterna sem nenhuma outra possibilidade de salvação. (Efésios 1.3-8; Romanos 5.18; Marcos 16.15-16; I Timóteo 2.3-6 e II Pedro 3.9).</p>

            <p>10. Na libertação do poder do pecado que Cristo alcançou para os homens, não só aniquilando o pecado, como também incluindo todo ser humano em sua morte e ressurreição, destruindo sua natureza pecaminosa os regenerando para andar em novidade de vida. (Romanos 8.1-3; Romanos 6.6; Colossenses 2.11; I Pedro 1.3 e Colossenses 3.1-3). </p>

            <h3><b>VIII. O Novo Nascimento</b></h3>

            <p>11. No novo nascimento, como absolutamente imprescindível para que o homem experimente a totalidade desta poderosa salvação, o qual acontecerá pela fé e confissão da Palavra de Deus, fazendo com que a verdade de sua morte e ressurreição com Cristo se torne uma realidade pessoal no poder do Espírito Santo. (João 3.3-6; Romanos 10.10; Tiago 1.18; I Pedro 1.23 e Tito 3.4-7). </p>

            <h3><b>IX. O Aperfeiçoamento dos Santos</b></h3>

            <p>12. No aperfeiçoamento dos santos que embora livres do poder do pecado, ainda poderão pecar não mais por escravidão ou como fruto de uma natureza perversa, como exceção e não como regra, mas em decorrência de estarem no processo de alcançar o alvo da soberana vocação de Deus em Cristo Jesus, o que implica em um crescente despojar-se do velho homem e revestir-se do novo homem, dentro da comunhão dos santos (Romanos 6.14 e 17-18; Filipenses 3.12-14; Efésios 4.22-24; Colossenses 3.1-10 e I João 2.1-2). </p>

            <h3><b>X. A Doutrina dos Batismos</b></h3>

            <p>13. No batismo nas águas, em nome do Pai, do Filho e do Espírito Santo, como confissão pública da fé e testemunho externo da experiência interior de nossa morte e ressurreição juntamente com Cristo. (Mateus 28.19 e I Pedro 3.21).</p>
            <p>14. No batismo no Espírito Santo, que deve se seguir ao novo nascimento embora seja uma experiência distinta deste, como sendo o primeiro passo para o regenerado viver diariamente deixando-se encher pelo Espírito, para expressar em sua vida o amor e o poder de Deus, através do fruto e dos dons do Espírito Santo, sendo com isto uma verdadeira testemunha do Senhor Jesus. (Mateus 3.11; Atos 1.8; Atos 2.1-4; Atos 8.14-16; Efésios 5.18; I Coríntios 12.7-11 e Gálatas 5.22).</p>

            <h3><b>XI. A Santidade da Vida Cristã</b></h3>

            <p>15. Na santidade da vida cristã, pois que cada salvo de posse do novo nascimento e da vida no Espírito Santo pode viver agora no temor do Senhor, através de uma vida diária de comunhão com a Palavra e de oração, crescendo na graça e no conhecimento de Cristo, sendo transformado de fé em fé e de glória em glória na imagem e semelhança do Senhor. (II Coríntios 3.18; I Tessalonicenses 5.23-24 e Filipenses 1.6).</p>

            <h3><b>XII. A Igreja</b></h3>
            <p>16. Na Igreja, expressão visível do Corpo de Cristo aqui na terra, gerada, edificada e governada pelo Senhor Jesus, seu Cabeça e único fundamento lançado pelos apóstolos e profetas. (Efésios 1 e 4).</p>


            <p>17. Na unidade do Corpo de Cristo, sua Igreja, pois apesar das diversidades de denominações e ministérios, ela foi consignada por Jesus lá na cruz, pois no seu corpo ele destruiu todas as barreiras de separação e de ambos os povos (judeus e todos os demais povos) fez um, cabendo a nós proclamar, celebrar e desfrutar desta unidade. (Efésios 2.14-16 e Efésios 4.4-6).</p>


            <p>18. Na adoração a Deus como sendo o mais elevado propósito para o qual a Igreja foi criada e na evangelização e no fazer discípulos, como sendo a sua suprema missão aqui na terra, a qual deve atingir todas as nações. (Efésios 1.4-6; Efésios 3.20-21 e Mateus 28.18-20).</p>


            <p>19. No amor, como sendo a verdadeira característica da vida em comunhão dos santos na Igreja, o qual deve ser expresso através de relacionamentos cada vez mais significativos que levem os salvos a ter uma unidade tão perfeita de alma, que “todos pensem e sintam do mesmo modo”, causando com isto um grande impacto nos perdidos, a fim de que creiam no evangelho. (João 13.34-35; João 17.22-23; Atos 4.32 e Filipenses 2.1-4). </p>


            <h3><b>XIII. Os Pequenos Grupos</b></h3>

            <p>20. Na comunhão em pequenos grupos nos lares, como sendo o coração da igreja local, o ambiente mais apropriado para os salvos viverem em amor como família, desenvolvendo relacionamentos e assim juntos exaltando ao Senhor, edificando-se uns aos outros e evangelizando os perdidos, concretizando a visão que o Senhor deu para a Comunidade da Graça de ser: “Uma igreja-família, vivendo o amor de Cristo, alcançando o próximo e formando discípulos”. (Atos 2.42-47). </p>

            <h3><b>XIV. O Sacerdócio Universal dos Salvos</b></h3>

            <p>21. No sacerdócio universal de todos os salvos, os quais, depois do novo nascimento (incluindo o batismo nas águas e do batismo no Espírito Santo), devem ser ensinados, discipulados e treinados nos grupos pequenos e no relacionamento individual, para que possam ser capacitados e enviados para que cumpram, com muito sucesso, a grande comissão de ir e fazer discípulos de todas as nações, multiplicando número dos filhos de Deus na terra, restaurando-se assim plenamente o Propósito Eterno de Deus (semelhança, governo e multiplicação). (Mateus 28.18-20).</p>

            <h3><b>XV. A Ceia do Senhor</b></h3>

            <p>22. Na Ceia do Senhor, como expressão máxima de nossa aliança com o Senhor e uns com os outros, onde, pela presença espiritual de Cristo através do pão e do vinho, cada salvo pode experimentar e se apropriar de todos os benefícios do sacrifício de Cristo: perdão, nova vida, cura divina, libertação, quebra de barreiras etc., recebendo a promessa do Senhor: “... quem de mim se alimenta por mim viverá”. (João 6.53-57). </p>

            <h3><b>XVI. A Família</b></h3>

            <p>23. Na família, como sendo a instituição divina prioritária para a realização do Projeto Eterno de Deus na terra, que deve ser formada pelo casamento indissolúvel entre duas pessoas de sexos diferentes, a qual firmada nos princípios da Palavra de Deus suscitará uma descendência de piedosos que irá estabelecer o Reino de Deus neste mundo, sendo que por esta causa a Igreja deve continuamente protegê-la, edificá-la e defendê-la de todos os instrumentos diabólicos usados para sua destruição (homossexualismo, divórcio, adultério, fornicação, pornografia, aborto etc.). (Gênesis 1.26-28; Gênesis 2.18-24; Gênesis 12.1-3 e Mateus 19.3-6). </p>

            <h3><b>XVII. O Sustento da Obra de Deus</b></h3>

            <p>24. No sustento da obra de Deus, através dos dízimos e ofertas, que são princípios divinos estabelecidos desde os primórdios da humanidade (Gênesis 14 e 28), muito antes da Velha Aliança e que devem ser praticados por cada salvo como um grande privilégio de prover recursos financeiros para a obra de Deus em toda terra, vivenciando o eterno princípio divino de que mais bem aventurado é dar do que receber. (Malaquias 3.8-10 e Mateus 23.23).</p>

            <h3><b>XVIII. As Boas Obras</b></h3>

            <p>25. No cuidado dos pobres, viúvas, órfãos, carentes, necessitados e excluídos do sistema social, através da Igreja, como sendo uma demonstração inevitável do amor de Cristo que deve acompanhar a evangelização, consubstanciando-se assim a visão da missão integral, que é a tarefa suprema de cada cristão. (Mateus 25.31-46; Atos 6.1-3 e Gálatas 2.9-10). </p>

            <h3><b>XIX. A Participação na Vida Pública</b></h3>

            <p>26. Na atuação da Igreja, na vida política da nação, contribuindo para o estabelecimento de uma verdadeira justiça social, pautando-se sempre por uma ação profética e ética baseada nos princípios da Palavra de Deus, a fim de ser “sal da terra e luz do mundo” dentro de todas as instâncias de poder de um sistema de governo democrático. (Provérbios 28.12 e 28; Provérbios 29.7-8 e Daniel 4.27). </p>

            <h3><b>XX. A Volta de Cristo</b></h3>

            <p>27. Na volta de Cristo, quando se dará a ressurreição e o arrebatamento dos salvos, inaugurando o milênio quando Ele implantará seu reino em toda a terra e Satanás estará em cadeias no abismo, seguindo-se depois a ressurreição dos ímpios, o juízo final, o lago de fogo e enxofre onde o diabo, seus anjos, todos os demônios e os ímpios padecerão na condenação eterna, e por fim, os novos céus e a nova terra onde a totalidade dos salvos viverá eternamente com o Senhor na Jerusalém Celestial. (Mateus 24.1-44 e Apocalipse 19-22).</p>

            </div>

        </div>
    </div>
</section>
<!--  //CONTEUDO  -->