<!--  PAGE NAME  -->
<section class="page-name" data-scroll-index="1">
    <h1>a família de deus</h1>
    <div class="bread-crumbs uppercase">
        <a href="./teologia">teologia</a>
        <a href="./visao">visão</a>
        <a href="./valores">os valores da visão</a>
        <a href="./missao">missão</a>
        <a href="./modelo">modelo ide</a>
        <a href="./logo">significado da logo</a>
        <a href="./associacao">a associação</a>
        <a href="./fundacao">a fundação</a>
        <a href="./declaracao">declaração de fé</a>
    </div>
    <div class="image-wrapper images-bg">
        <img alt="" src="/assets/frontend/images/secondary-page/1.jpg">
    </div>  
</section>
<!--  //PAGE NAME  -->

<!-- CONTEUDO  -->
<section class="blog-list">
    <div class="container">
        <div class="row">

            <div class="col-md-12 theme-color">

            <p>A vontade de Deus é que vivamos numa família, onde te­nhamos relacionamentos uns com os outros. Jamais foi plano de Deus que sua igreja fosse um clube, onde simplesmente as pessoas se reúnam para uma atividade agradável. Não é da vontade de Deus que seus filhos andem isolados. Ele deseja que estejamos ligados ao corpo de Cristo.</p>
            <p><i class="fa fa-circle"></i> No entanto as pessoas trazem para a igreja a visão distor­cida dos relacionamentos que ocorrem em seus lares. Muitos desses relacionamentos estão destruídos. Por viverem esta realidade em seus lares, as pessoas chegam à igreja com a mesma dificuldade de se relacionar.</p>
            <p><i class="fa fa-circle"></i> Agora que somos filhos de Deus, libertados da antiga maneira de viver, podemos aprender o modo correto de nos relacionarmos com nossos irmãos e familiares. A Palavra de Deus e a comunhão com outros cristãos é a forma pela qual vamos aprender realmente a viver como uma família.</p>
            <p><i class="fa fa-circle"></i> A vida no reino de Deus é essencialmente uma vida de relacionamentos sadios e equilibrados. Os cristãos vivem no dia a dia o amor de Cristo. Ao contrário do que muitos imaginam, essa vida é prática e muito simples de ser vivida.</p>

            <h3><strong>Benefícios da vida em família</strong></h3>

            <h3><b>Compartilhamos nossas necessidades básicas e recebemos proteção</b></h3>

            <blockquote>
                <p>Quando conhecemos as necessidades básicas uns dos outros, encontramos proteção, cobertura e o caminho para a solução daquelas necessidades.</p>
                <p>Quando ajudamos os outros nos sentimos úteis. Ganha­mos o senso de pertencer a um grupo. Somos valorizados re­cebendo ajuda ou podendo oferecer ajuda, em amor. Ao invés de sermos expostos e envergonhados, encontramos auxílio e proteção mútua pela oração, intercessão, aconselhamento e pelo suprimento material. Não estamos mais sozinhos e o inimigo não pode nos surpreender. Somos todos um exército lutando em favor um do outro no nome de Jesus.</p>
            </blockquote>

            <h3><strong>Como Participar desta Família?</strong></h3>

            <p>Algumas maneiras pelas quais você pode receber assis­tência nesta família:</p>

            <p><i class="fa fa-circle"></i>Cultos de celebração: neles você recebe inspiração, pa­lavras de Deus, orações, unção, encorajamento e desafios. É um tempo especial de louvor e adoração a Deus. É onde, juntos, como família, ouvimos as orientações gerais para prosseguirmos e alcançarmos objetivos comuns.</p>

            <ul>
                <h3><strong>Horários de Cultos:</strong></h3>
                <li>Domingos - 9hs e 19hs</li>
                <li>Sábados - às 20hs - Culto de Jovens (Exceto nos últimos sábados do mês)</li>
                <li>Sábados - às 17:30hs - Reunião com Adolescentes</li>
                <li>Quintas-feiras - às 20hs</li>
            </ul>
            <p>1ª Quartas-feiras do Mês: Reuniões de Mulheres Intercessoras Local: Av. Rio Branco, 191 - Londrina - PR.</p>

            <p><i class="fa fa-circle"></i>Reuniões dos ministérios: são grupos de interesses comuns, que possuem uma liderança especializada para orientá-lo de acordo com sua necessidade e prepará-lo pra alcançar outros. Estamos estruturados da seguinte forma: casais, jovens, noivos, adolescente, crianças, mulheres e música.</p>

            <p><i class="fa fa-circle"></i>Grupos GCEM: são encontros semanais que acon­tecem nas casas dos membros da comunidade. Estes pequenos grupos têm por objetivo praticar os valores da igreja-família, tais como: amor, companheirismo, cuidado mútuo e a evangelização de pessoas de nosso relacionamento.</p>



            </div>

        </div>
    </div>
</section>
<!--  //CONTEUDO -->