<!--  PAGE NAME  -->
<section class="page-name" data-scroll-index="1">
    <h1>a fundação</h1>
    <div class="bread-crumbs uppercase">
        <a href="./teologia">teologia</a>
        <a href="./visao">Visão</a>
        <a href="./valores">os valores da visão</a>
        <a href="./missao">missão</a>
        <a href="./familia">a família de deus</a>
        <a href="./modelo">modelo ide</a>
        <a href="./logo">significado da logo</a>
        <a href="./associacao">a associação</a>
        <a href="./declaracao">declaração de fé</a>
    </div>
    <div class="image-wrapper images-bg">
        <img alt="" src="/assets/frontend/images/secondary-page/1.jpg">
    </div>  
</section>
<!--  //PAGE NAME  -->

<!--  CONTEUDO  -->
<section class="blog-list">
    <div class="container">
        <div class="row">

            <div class="col-md-12 theme-color">

                <p>Somos uma entidade de promoção social, cuja visão e desafio estão em alcançar e resgatar o próximo. Estamos empenhados em recuperar a integridade e a dignidade de cada um, baseados nos valores cristãos que pregam a justiça social.</p>

                <p>Iniciamos nossos trabalhos em 1982 e, com o decorrer do tempo, fomos crescendo e vendo o nosso sonho ser concretizado. A partir de 1996, com o nome de Fundação Comunidade da Graça, novos projetos sociais foram criados, com o apoio e o trabalho de muitos voluntários.</p>

                <p>Hoje somos mais de 180 voluntários atuantes, entre profissionais, médicos, dentistas, psicólogos, assistentes sociais, fonoaudiólogos, enfermeiros, pedagogos, empresários, comerciantes e pessoas da comunidade em geral.</p>

                <p>Cada um se empenha e contribui com seu tempo, suas habilidades, disponibilidades, recursos e amor para atender crianças, adolescentes, idosos e famílias por meio dos projetos assistenciais.</p>
                <p>Sabemos que a maioria dos problemas sociais brasileiros são difíceis de solucionar. Porém, como agentes de transformação que somos, acreditamos poder contribuir com ações positivas na construção de um Brasil mais justo.</p>

                <h3><strong>Aqui funcionam os seguintes trabalhos:</strong></h3>
                <ul>
                    <li><h4><i class="fa fa-circle"></i> Sede;</h4></li>
                    <li><h4><i class="fa fa-circle"></i> Administração;</h4></li>
                    <li><h4><i class="fa fa-circle"></i> Voluntariado;</h4></li>
                    <li><h4><i class="fa fa-circle"></i> Saúde da Mulher;</h4></li>
                    <li><h4><i class="fa fa-circle"></i> Policlínicas Caritas;</h4></li>
                    <li><h4><i class="fa fa-circle"></i> Programa Dorcas (Comunarte).</h4></li>
                </ul>
            </div>

        </div>
    </div>
</section>
<!--  //CONTEUDO  -->