<!--  PAGE NAME  -->
<section class="page-name" data-scroll-index="1">
    <h1>significado da logo</h1>
    <div class="bread-crumbs uppercase">
        <a href="./teologia">teologia</a>
        <a href="./visao">visão</a>
        <a href="./valores">os valores da visão</a>
        <a href="./missao">missão</a>
        <a href="./familia">a família de deus</a>
        <a href="./modelo">modelo ide</a>
        <a href="./associacao">a associação</a>
        <a href="./fundacao">a fundação</a>
        <a href="./declaracao">declaração de fé</a>
    </div>
    <div class="image-wrapper images-bg">
        <img alt="" src="/assets/frontend/images/secondary-page/1.jpg">
    </div>  
</section>
<!--  //PAGE NAME  -->

<!--  CONTEUDO  -->
<section class="blog-list">
    <div class="container">
        <div class="row">

            <div class="col-md-12 theme-color">

            <img src="/assets/frontend/images/logo-info.jpg" alt="" class="img-responsive" style="margin: 0 auto;">

            <h3><strong>Uma Igreja-Família, vivendo o amor de Cristo, alcançando o próximo e formando discípulos”.</strong></h3>

            <h3><b>Uma Igreja-Família é representada:</b></h3>

                <p><i class="fa fa-circle"></i> Pelos peixes grandes que estão entrelaçados;</p>
                <p><i class="fa fa-circle"></i> Pelos Peixes em forma de dois anéis sobrepostos, lembrando a idéia de aliança.</p>

            <h3><b>Vivendo o amor de Cristo é representado:</b></h3>

                <p><i class="fa fa-circle"></i> Pela proximidade dos peixes e o seu entrelaçamento entre si;</p>
                <p><i class="fa fa-circle"></i> Pelos Peixes em forma de dois anéis sobrepostos, lembrando a idéia de aliança.</p>

            <h3><b>Alcançar o próximo está representado:</b></h3>

                <p><i class="fa fa-circle"></i> Pela idéia de movimento dos peixes;</p>
                <p><i class="fa fa-circle"></i> Por estarem lado a lado, os maiores com os menores.</p>

            <h3><b>Fazer discípulos está representado:</b></h3>

                <p><i class="fa fa-circle"></i> Pelos peixes pequenos seguindo os grandes, significando que o discipulado é aprendido pelo exemplo de vida;</p>
                <p><i class="fa fa-circle"></i> E pelos dois peixes grandes com a cabeça próxima, mostrando que todos precisam estar sendo discipulados e orientados, mesmo os mais maduros.</p>

            </div>

        </div>
    </div>
</section>
<!--  //CONTEUDO  -->