<!--  PAGE NAME  -->
<section class="page-name" data-scroll-index="1">
    <h1>missão</h1>
    <div class="bread-crumbs uppercase">
        <a href="./teologia">teologia</a>
        <a href="./visao">visão</a>
        <a href="./valores">os valores da visão</a>
        <a href="./familia">a família de deus</a>
        <a href="./modelo">modelo ide</a>
        <a href="./logo">significado da logo</a>
        <a href="./associacao">a associação</a>
        <a href="./fundacao">a fundação</a>
        <a href="./declaracao">declaração de fé</a>
    </div>
    <div class="image-wrapper images-bg">
        <img alt="" src="/assets/frontend/images/secondary-page/1.jpg">
    </div>  
</section>
<!--  //PAGE NAME  -->

<!--  CONTENT  -->
<section class="blog-list">
    <div class="container">
        <div class="row">

            <div class="col-md-12 theme-color">

            <p>Como parte do corpo de Cristo, a Missão da Comunidade da Graça, é evangelizar e discipular muitas pessoas, pois o Pai deseja que a sua família aqui na terra seja composta de “muitos filhos semelhantes a Jesus” (<b>Romanos 8:29-30</b>); fazendo isto estaremos cumprindo a nossa Missão que é a de pregar o evangelho e fazer discípulos.</p>

            <p>A Missão define a razão de existir de uma organização. A missão responde às seguintes perguntas:</p>

            <p><i class="fa fa-circle"></i> Por que existimos?</p>

            <p><i class="fa fa-circle"></i> Qual o nosso propósito?</p>

            <p>Ao concluir seu ministério na terra, antes de subir aos céus, o Senhor Jesus deixou claro qual é a missão de sua igreja:</p>

            <p><i class="fa fa-circle"></i> Ir e Pregar; o que significa que a igreja (nós), não deve ficar passiva, esperando, mas tomar a iniciativa. Pregar significa proclamar as boas novas do evangelho (kerigma) de Cristo.(<b>Marcos 16:15</b>)</p>

            <p><i class="fa fa-circle"></i> Fazer discípulos ensinando-os o que Jesus nos ordenou (didake) em sua Palavra. (<b>Mateus 28:19-20</b>)</p>

            <p>A palavra discípulo significa ser um aprendiz. Tal como Jesus, nós devemos ensinar a outros, porque fazer discípulos é essencialmente um relacionamento entre duas pessoas.</p>

            <p>Discipulado não é apenas ensino em sala de aula. Ensino nesta passagem significa, além do estudo bíblico, instruir a outro a partir do seu exemplo de vida e de seu relacionamento pessoal com Deus.</p>

            <h3><strong>Ensinar e aprender são um relacionamento, não uma técnica.</strong></h3>

            <h3>Jesus ordenou a sua igreja que fizesse o mesmo que ele fez, que apenas seguisse os seus passos. Entretanto, para fazermos isso de coração, do íntimo, nós devemos também valorizar as mesmas coisas que Jesus valorizou, e priorizá-las da mesma forma.</h3>
            <h3>Para tanto este é o nosso alvo: que cada membro da Comunidade da Graça se torne um discípulo maduro, cada vez mais semelhante à Cristo, capacitado a fazer outros discípulos de Jesus.</h3>

            </div>

        </div>
    </div>
</section>
<!--  //CONTENT  -->