<!--  PAGE NAME  -->
<section class="page-name" data-scroll-index="1">
    <h1>MODELO IDE</h1>
    <div class="bread-crumbs uppercase">
        <a href="./teologia">teologia</a>
        <a href="./visao">visão</a>
        <a href="./valores">os valores da visão</a>
        <a href="./missao">missão</a>
        <a href="./familia">a família de deus</a>
        <a href="./logo">significado da logo</a>
        <a href="./associacao">a associação</a>
        <a href="./fundacao">a fundação</a>
        <a href="./declaracao">declaração de fé</a>
    </div>
    <div class="image-wrapper images-bg">
        <img alt="" src="/assets/frontend/images/secondary-page/1.jpg">
    </div>  
</section>
<!--  //PAGE NAME  -->

<!--  CONTENT  -->
<section class="blog-list">
    <div class="container">
        <div class="row">

            <div class="col-md-12 theme-color">

            <h3><strong>Funcionamento da CG</strong></h3>

            <p>Nosso objetivo é ganhar almas e fazer discípulos. Para isso precisamos de uma estratégia, um modelo.</p>

            <img src="/assets/frontend/images/modelo-ide.jpg" alt="" class="img-responsive" style="margin: 0 auto;">

            <p>O modelo nada mais é do que uma estratégia para que possamos atingir nossa visão. Batizamos nosso modelo de IDE, que significa:</p>
            <ul>
                <li><h3><strong>I</strong><b>ntegrar</b></h3></li>
                <li><h3><strong>D</strong><b>esenvolver</b></h3></li>
                <li><h3><strong>E</strong><b>nviar</b></h3></li>
            </ul>
            <p>Usamos esta sigla para facilitar a memorização e também para que todos saibam qual o trajeto que um membro segue na Comunidade da Graça.</p>

            <h3><b>O que é "integrar”?</b></h3>

                <p><i class="fa fa-circle"></i> Evangelizar a pessoa e levá-la a uma experiência de novo nascimento;</p>
                <p><i class="fa fa-circle"></i> Integrá-la nos cultos e no GCEM, iniciando o discipulado pessoal;</p>
                <p><i class="fa fa-circle"></i> Levá-la a participar do Encontro Bem-Vindo, que é muito importante para a pessoa experimentar libertação interior e cura;</p>
                <p><i class="fa fa-circle"></i> Compartilhar com ela os princípios básicos da vida cristã, usando o livro "Formando Discípulos";</p>
                <p><i class="fa fa-circle"></i> Batismo nas águas;</p>
                <p><i class="fa fa-circle"></i> Batismo no Espírito Santo.</p>
                <p><i class="fa fa-circle"></i> O processo de integrar está ilustrado na figura do nosso modelo.</p>

            <h3><b>O que é "desenvolver"?</b></h3>

                <p><i class="fa fa-circle"></i> Ensinar os princípios básicos para uma vida bem sucedida (pessoal, familiar, social, profissional e ministerial);</p>
                <p><i class="fa fa-circle"></i> Discipular um a um: pastorear a pessoa individualmente (desenvolvendo relacionamento intencional), ensinando de maneira prática como aplicar em sua vida os princípios que tem aprendido;</p>
                <p><i class="fa fa-circle"></i> Identificar dons e talentos: levar a pessoa a descobrir seu chamado pessoal, os dons e talentos que Deus lhe deu para servir ao próximo;</p>
                <p><i class="fa fa-circle"></i> Compartilhar com ela os princípios básicos da vida cristã, usando o livro "Formando Discípulos";</p>
                <p><i class="fa fa-circle"></i> Batismo nas águas;</p>
                <p><i class="fa fa-circle"></i> Batismo no Espírito Santo.</p>

            <p>Para ajudar neste processo a pessoa precisa:</p>
                <p><i class="fa fa-circle"></i> Estar num grupo;</p>
                <p><i class="fa fa-circle"></i> Ter amigos mais maduros que possam ajudá-la a conhecer e praticar a Palavra de Deus;</p>
                <p><i class="fa fa-circle"></i> Participar das atividades de ensino e treinamento da igreja de acordo com sua necessidade (noivos, namorados, família, finanças, etc.).</p>

            <h3><b>O que é "enviar"?</b></h3>

            <p>Enviar é a fase em que preparamos a pessoa para atuar no ministério, servindo a outros como dirigente de grupo, diácono, etc. Enviar compreende:</p>
                <p><i class="fa fa-circle"></i> Treinar para liderança;</p>
                <p><i class="fa fa-circle"></i> Fazer outros discípulos;</p>
                <p><i class="fa fa-circle"></i> Discipulado mais profundo.</p>

            <h3>O IDE é algo progressivo. Começa com o não cristão e termina com um líder que também gera outros para Cristo.</h3>

            </div>

        </div>
    </div>
</section>
<!--  //CONTENT  -->