<!--  PAGE NAME  -->
<section class="page-name" data-scroll-index="1">
    <h1>TEOLOGIA</h1>
    <div class="bread-crumbs uppercase">
        <a href="./visao">Visão</a>
        <a href="./valores">os valores da visão</a>
        <a href="./missao">missão</a>
        <a href="./familia">a família de deus</a>
        <a href="./modelo">modelo ide</a>
        <a href="./logo">significado da logo</a>
        <a href="./associacao">a associação</a>
        <a href="./fundacao">a fundação</a>
        <a href="./declaracao">declaração de fé</a>
    </div>
    <div class="image-wrapper images-bg">
        <img alt="" src="/assets/frontend/images/secondary-page/1.jpg">
    </div>  
</section>
<!--  //PAGE NAME  -->

<!--  CONTENT  -->
<section class="blog-list">
    <div class="container">
        <div class="row">

            <div class="col-md-12 theme-color">

                <p>A teologia da Comunidade da Graça, firmada na Palavra de Deus, é baseada essencialmente na doutrina (ensino) cristã da regeneração em Cristo. A Comunidade da Graça crê e prega,de                         acordo com as palavras que o Senhor Jesus disse a Nicodemos, que o ser humano para ser salvo precisa nascer de novo:</p>

                <p><strong>“Em verdade, em verdade te digo que ninguém pode ver o reino de Deus se não nascer de novo” (João 3:3)</strong>.</p>

                <p>Regenerar significa exatamente isto: gerar (criar) de novo; Jesus deixou claro que o ser humano para ser salvo, precisa ser gerado, feito, criado de novo. Por isto, a Comunidade da Graça depois de examinar, provar e experimentar as Escrituras, durante muito tempo, guiada pelo Espírito Santo, elegeu a doutrina da regeneração, como sendo a única verdade que soluciona o maior problema do homem, a escravidão ao pecado, que impede a sua salvação eterna.</p>

                <p>As verdades bíblicas que justificam plenamente a importância máxima dessa doutrina são principalmente as seguintes:</p>

                <p><strong><i class="fa fa-circle"></i> O Propósito Eterno de Deus:</strong> de acordo com Gênesis 1:26-28, Deus criou o ser humano para ser moralmente semelhante a Ele refletindo a sua glória, para implantar o seu reino aqui na Terra e gerar para Ele uma grande descendência de filhos semelhantes a Jesus (Romanos 8:29).</p>

                <p><strong><i class="fa fa-circle"></i> As conseqüências do pecado na vida humana:</strong> o homem morreu espiritualmente passando a ser totalmente egoísta, tendo o seu corpo controlado por uma natureza que se tornou inimiga de Deus, rebelde e pecaminosa (a natureza carnal).</p>

                <p><strong><i class="fa fa-circle"></i> O sacrifício de Cristo:</strong> as riquezas da misericórdia de Deus e o seu grande amor por nós o levaram a sacrificar seu próprio filho Jesus, na cruz do Calvário, para nos dar uma poderosa salvação; esta salvação além de incluir a remissão / perdão dos nossos pecados, a cura divina, a quebra de maldições e muitos outros benefícios, conquistou para nós também o milagre da regeneração. A Palavra nos declara que para nos gerar de novo, Deus nos incluiu:</p>

                <p><i class="fa fa-plus"></i> Na morte de Jesus, quando foi crucificado com ele nosso velho homem egoísta e fomos despojados da natureza carnal, pela circuncisão de Cristo (João 12:32; II Coríntios 5:14; Romanos 6:6 e Colosensses 2:11).</p>
                <p><i class="fa fa-plus"></i> Na ressurreição de Cristo, quando ele nos deu um novo coração e um espírito novo, para que pudéssemos ser cheios do Espírito Santo (Efésios 2:1-6; I Pedro 1:3 e Ezequiel 36: 26-27).</p>

                <p><strong><i class="fa fa-circle"></i>O Projeto Eterno de Deus restaurado:</strong> quando o ser humano crê em seu coração nestas verdades do evangelho de Jesus e as confessa com sua boca, ele experimenta o milagre do novo nascimento e agora ele pode cumprir com o Projeto Eterno de Deus para a sua vida; ele readquire em Cristo a semelhança do Senhor, o reino (governo) de Deus se torna visível nele e por isto será muito bem sucedido na multiplicação dos discípulos de Jesus (Romanos 10:9-10; II Coríntios 3:18; Atos 11:24 e Mateus 28:18-20).</p>

                <p>A Teologia da Comunidade da Graça está totalmente vinculada à sua Visão e à sua Missão, pois biblicamente somente uma pessoa nascida de novo e cheia do Espírito é que pode viver em amor na família de Deus e cumprir com o desafio de fazer discípulos de Jesus.</p>

            </div>

        </div>
    </div>
</section>
<!--  //CONTENT  -->