<!--  PAGE NAME  -->
<section class="page-name" data-scroll-index="1">
    <h1>VALORES</h1>
    <div class="bread-crumbs uppercase">
        <a href="./teologia">teologia</a>
        <a href="./visao">visão</a>
        <a href="./missao">missão</a>
        <a href="./familia">a família de deus</a>
        <a href="./modelo">modelo ide</a>
        <a href="./logo">significado da logo</a>
        <a href="./associacao">a associação</a>
        <a href="./fundacao">a fundação</a>
        <a href="./declaracao">declaração de fé</a>
    </div>
    <div class="image-wrapper images-bg">
        <img alt="" src="/assets/frontend/images/secondary-page/1.jpg">
    </div>  
</section>
<!--  //PAGE NAME  -->

<!--  CONTENT -->
<section class="blog-list">
    <div class="container">
        <div class="row">

            <div class="col-md-12 theme-color">

                <h3><strong>Relacionamento com Deus</strong></h3>
                <p>Ser cristão é acima de tudo desenvolver um relacionamento pessoal com Deus através da oração, da meditação na Palavra e da comunhão com o Espírito Santo.
                (<b>João 14:23-26; I Samuel 15:22; Filipenses 4:6; João 15:16</b>)</p>

                <h3><strong>Relacionamento com a família</strong></h3>
                <p>Lares ajustados produzem uma igreja ajustada. O propósito de Deus é estabelecido através de famílias transformadas que vivem em amor e serviço, sendo modelo para outros. 
                (<b>Gênesis 12:1-3; Atos 16:31; Salmos 68:6; Efésios 2:19</b>)</p>

                <h3><strong>Relacionamento com os irmãos</strong></h3>
                <p>Viver em aliança, amor e fidelidade uns para com os outros, honrando e sujeitando-nos uns aos outros, é o que atrairá a glória de Deus para no nosso meio. 
                (<b>Salmos 133; Romanos 12:10; I João 4:7-8; Efésios 5:21;</b>)</p>

                <h3><strong>Serviço ao próximo (relacionando-se com os não cristãos)</strong></h3>
                <p>A compaixão e o serviço ao próximo é a chave para ganhar almas e cumprir a grande comissão. Quem ama, serve (Mateus 6:34; Marcos 10:45). Por isto para alcançarmos o nosso próximo com a mensagem do evangelho, antes precisamos expressar-lhe nosso amor e cuidado sincero. Também queremos uma igreja que seja relevante para a sociedade onde está inserida, importando-se com todos, especialmente aqueles que são desprezados, excluídos e não conhecem a graça de Deus.</p>

                <p>O atendimento das necessidades e do direito dos pobres, necessitados e excluídos da sociedade é também papel da igreja. (<b>Provérbio 28:27; Tito 3:8</b>)</p>

                <h3><strong>Discipular/preparar para o ministério</strong></h3>
                <p>A igreja deve capacitar seus membros para viver uma vida digna do evangelho de Cristo, atuar no serviço do Reino de Deus e influenciar outras pessoas, ensinando-os a guardar todas as coisas que Jesus nos ordenou.</p>

                <p>Cremos que o ensino ungido da Palavra de Deus e a capacitação pessoal são fundamentais para que cada cristão possa gerar novos convertidos e discípula-los. Cristãos edificados e fortalecidos irão influenciar o meio em que vivem. (<b>Efésios 4:11-12; Lucas 10:2</b>)</p>

                <h3><b>O grande desafio para os pastores / supervisores / dirigentes de GCEM, é levar cada membro da Comunidade da Graça a viver e praticar estes valores, através do pastoreio discipulado e ensino de cada um. Temos que ter isto em vista: na medida em que os membros da Comunidade da Graça forem vivendo e praticando estes valores, a Visão da Igreja Família se concretizará poderosamente em nosso meio.</b></h3>

            </div>

        </div>
    </div>
</section>
<!--  //CONTENT -->