<!--  PAGE NAME  -->
<section class="page-name" data-scroll-index="1">
    <h1>VISÃO</h1>
    <div class="bread-crumbs uppercase">
        <a href="./teologia">teologia</a>
        <a href="./valores">os valores da visão</a>
        <a href="./missao">missão</a>
        <a href="./familia">a família de deus</a>
        <a href="./modelo">modelo ide</a>
        <a href="./logo">significado da logo</a>
        <a href="./associacao">a associação</a>
        <a href="./fundacao">a fundação</a>
        <a href="./declaracao">declaração de fé</a>
    </div>
    <div class="image-wrapper images-bg">
        <img alt="" src="/assets/frontend/images/secondary-page/1.jpg">
    </div>  
</section>
<!--  //PAGE NAME  -->

<!--  CONTENT  -->
<section class="blog-list">
    <div class="container">
        <div class="row">

            <div class="col-md-12 theme-color">

                <h3><b>“Uma Igreja Família, vivendo o amor de Cristo, alcançando o próximo e formando discípulos.”</b></h3>

                <h3><strong>Uma Igreja Família</strong></h3>

                <p>Por que escolhemos ser uma Igreja Família? Por que esta é a vontade de Deus que deseja que seus filhos vivam em amor uns com os outros, para abençoar o mundo, através do seu estilo de vida. (<b>João 17:20-23</b>)</p>

                <p>Nossa visão se baseia no fato de que a Igreja é a família de DEUS, onde as pessoas têm relacionamentos de aliança e fidelidade, se preocupam umas com as outras, e os mais maduros cuidam e ensinam os mais jovens. (<b>Romanos 8:29; Efésios 1:5-6; 3:14-15;</b>)</p>

                <h3><strong>Vivendo o Amor de Cristo</strong></h3>

                <p>A Igreja família é o lugar onde as pessoas se amam como o Senhor Jesus nos ordenou. A igreja é um lugar de aceitação, não de exclusão. As pessoas são amadas sem distinção de cor, raça, sexo, idade,condição social, saúde física.</p>

                <p>Vivendo o amor de Cristo significa amar e servir as pessoas como o próprio Jesus faria, pois a igreja é o Corpo cuja cabeça é Cristo. (<b>João 13:34; João 15:12; I João 3:23</b>)</p>

                <h3><strong>Alcançando o Próximo</strong></h3>

                <p>A missão da igreja é ir e alcançar a todos os homens, fazendo deles discípulos (aprendizes) de Jesus Cristo, levando-os a um íntimo relacionamento com ele, para que se tornem cada vez mais semelhantes a Jesus.</p>

                <p>Alcançar o próximo significa evangelizar as pessoas com as quais nos relacionamos, a partir de nossa família (cônjuge, filhos), amigos, familiares, colegas de escola, de trabalho, vizinhos, e assim por diante. (<b>João 3:17; Mateus 18:11; Marcos 16:15</b>)</p>

                <h3><strong>Formando Discípulos</strong></h3>

                <p>O propósito principal da Igreja é fazer discípulos, pessoas que são semelhantes a Cristo em seu caráter e obras, e que têm o Espírito Santo habitando em seus corações. Para isso, é necessário ensinar aos novos convertidos tudo o que Jesus nos deixou, através da igreja local, dos pequenos grupos (GCEMs), e do discipulado individual.</p>

                <p>A Comunidade da Graça tem como visão fazer de cada membro um discípulo semelhante ao seu Senhor Jesus. Uma pessoa madura, capaz de amar a Deus, viver em amor, também alcançando a outros, fazendo deles discípulos de Cristo. (<b>Mateus 28:19-20</b>).</p>

            </div>

        </div>
    </div>
</section>
<!--  //CONTENT  -->