<div class="page-container">

    <div class="main-content">

        <div class="row">
            <div class="col-sm-12">
                <a href="/admin/midia/adicionar/video/">
                    <button class="btn btn-secondary btn-icon btn-icon-standalone btn-icon-standalone-right pull-right"><i class="fa-plus"></i><span>Adicionar</span></button>
                </a>
            </div>
            
            <div class="col-sm-12">
					
				<div class="xe-widget xe-conversations">
                    <div class="xe-bg-icon">
                        <i class="fa-calendar"></i>
                    </div>
                    <div class="xe-header">
                        <div class="xe-icon">						
                            <i class="fa-calendar"></i>
                        </div>
                        <div class="xe-label">
                            <h3>
                                Videos
                                <small>Videos Cadastradas</small>
                            </h3>
                        </div>
                    </div>
                    
				    <div class="xe-body">
				        <input type="text" class="form-control form-focus-info full-width" id="search_wdg" placeholder="Search ... ">
                        <ul class="list-unstyled" id="list-unstyled">

                            <?php foreach($videos as $video): ?>
                            <li>
                                <div class="xe-comment-entry">
                                    <a href="/admin/midia/editar/video/<?=$video->_;?>" class="xe-user-img">
                                        <img src="//img.youtube.com/vi/<?=$video->vi;?>/hqdefault.jpg" class="img-circle" width="80" height="80">
                                    </a>
                                    <div class="xe-comment"> 
                                        
                                        <div class="col-md-9">
                                            <a href="/admin/midia/editar/video/<?=$video->_;?>" class="xe-user-name"> 
                                                <strong><?=$video->title;?></strong>
                                            </a>
                                            <div class="form-group inline">
                                                <span class="badge badge-primary" style="font-size: 12px">
                                                    <i class="fa-clock-o"></i> <?=(new DateTime($video->date))->format("d/m/Y \a\s H:i");?>
                                                </span>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <a href="/admin/midia/remover/video/<?="{$video->_}/{$csrf}";?>">
                                                <button class="btn btn-danger btn-icon btn-icon-standalone btn-icon-standalone-right pull-right"><i class="fa-close"></i><span>Remover</span></button>
                                            </a>
                                            <a href="/admin/midia/editar/video/<?=$video->_;?>">
                                                <button class="btn btn-info btn-icon btn-icon-standalone btn-icon-standalone-right pull-right"><i class="fa-pencil"></i><span>Alterar</span></button>
                                            </a>
                                        </div>
                                        
                                    </div> 
                                </div>
                            </li>
                            <?php endforeach; ?>

                        </ul>
						</div>
                        
					</div>
					
				</div>
			</div>

    </div>

</div>
<?php $this->flashSession->output(); ?>